### ISSUE TITLE
FlutterSerialCOmmunicationPlugin.java shall explicitly register RECEIVER_EXPORTED when registering intent

### ISSUE THREAD

**Issue by ivan2angelov** [farellsujanto/flutter_serial_communication#14]
Unfortunately release v0.2.5 does not solve the issue.
I made Flutter app (it is very much the same as the example app in library code), build it and I get following error:
`Exception has occurred.
PlatformException (PlatformException(error, com.example.flutter_application_1: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.example.flutter_application_1: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`

here is the pubspec.yaml I have:
```
name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_serial_communication: ^0.2.5
  plugin_platform_interface: '>=2.0.0 <2.1.5'
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

When I build the app I made sure that flutter_serial_communication is indeed 0.2.5 -  I checked the dependency file ./app/intermediates/flutter/debug/flutter_build.d and it contains:
```
C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\LICENSE C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\flutter_serial_communication.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\flutter_serial_communication_method_channel.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\flutter_serial_communication_platform_interface.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\models\\device_info.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\leak_tracker-10.0.4\\LICENSE
```

What I find interesting is that if I build locally the library downloaded from GitHub it works, but if I use it via pubspec.yaml it fails.

On Android 14 there seems to be a change in handling broadcasting events, see
https://stackoverflow.com/questions/77235063/one-of-receiver-exported-or-receiver-not-exported-should-be-specified-when-a-rec

similar bug reported on https://github.com/react-native-share/react-native-share/issues/1463

I will thus open a new issue.

_Originally posted by @ivan2angelov in https://github.com/farellsujanto/flutter_serial_communication/issues/8#issuecomment-2120217911_
